### ISSUE TITLE
Height issue

### ISSUE THREAD

**Issue by lubomirblazekcz** [alexmacarthur/slide-element#19]
# Proposed Feature or Bug

When the content inside wrapper is updated and height is changed, the height is not updated. I think it would be better to add height: auto, once the wrapper is fully open. And upon closing update the height again?

**Comment by cnaa97** [comment]
+1

**Comment by cnaa97** [comment]
@alexmacarthur  In my case, when each children (li element) has different height size or fluid (like iframe youtube video, image load dynamically) this problem has occurred

**Comment by cnaa97** [comment]
<img width="763" alt="Screen Shot 2021-09-09 at 6 20 09 PM" src="https://user-images.githubusercontent.com/7259107/132659402-6b2e3c14-e8d1-4015-a7e3-52344da679a7.png">

**Comment by lubomirblazekcz** [comment]
For me is the issue with any dynamic content iside the wrapper. And that could be anything, adding removing items, textarea or something with fluid height as @cnaa97 mentioned.

**Comment by alexmacarthur** [comment]
Sorry for the delay on this, @lubomirblazekcz + @cnaa97! Fixed in the latest release: 

https://github.com/alexmacarthur/slide-element/releases/tag/v2.2.2
