### ISSUE TITLE
It doesn't slide, it only shows/hides the element

### ISSUE THREAD

**Issue by LuBreGit** [alexmacarthur/slide-element#26]
I just checked the landing page (https://alexmacarthur.github.io/slide-element/) and it doesn't work? It just shows or hides the target element, no slide effect applied. Tested on Chtome and Firefox on Windows 10, latest versions.

**Comment by alexmacarthur** [comment]
Interesting... I just tested it in Firefox, Safari, Chrome, and Brave, and all of them work as expected. To be clear, it's the code snippets that should be sliding open & closed. Are those the elements you're having a problem with?

**Comment by LuBreGit** [comment]
Hi Alex,

I am referring to the CodePen demo, here:

https://codepen.io/alexmacarthur/pen/VwpEgom

When I click "Slide it down" (first button on the left) or "Toggle it" (last button, on the right) I can see the blue boxes appear without animation. It's like a simple display:none active/inactive. That happens on Firefox, Edge and Chrome on Windows, latest versions. There is no animation.

This also happens on your main page, here:

https://alexmacarthur.github.io/slide-element/

When I click the three blue buttons "Show code" they don't animate the code boxes. They just appear/disappear.

**Comment by alexmacarthur** [comment]
Hm... I'm still not able to replicate this issue. Here's what I'm seeing. Would you mind sharing a screenshot of what you see if you get a moment? 

![slide-element-site](https://user-images.githubusercontent.com/8398220/148585059-d6b9d851-1087-4827-928b-2faf0f77de01.gif)

**Comment by LuBreGit** [comment]
I really can't find why it doesn't work, here's what I see on Chrome/Firefox/Edge:

https://youtu.be/Yxxp5oKJopw

**Comment by LuBreGit** [comment]
I tested it again on the following browsers (on Windows):

**Chrome** Version 97.0.4692.71 (Official Build) (64-bit)
**Firefox** Version 96.0.1 (64 bit)
**Edge** Version 97.0.1072.62 (Official build) (64-bit)

I've tried both _regular_ and _incognito_ modes with no addons enabled.

**Comment by paulovieira** [comment]
Could it be because of some setting in your browser / operating system related to `prefers-reduced-motion`?

In the developer console, what is the output of the following expression?

```js
window.matchMedia("(prefers-reduced-motion: reduce)").matches
```

If it's `true`, duration is set to 0.

**Comment by LuBreGit** [comment]
Just checked it, I confirm it's set to true on every browser. Why, though? I never touched it, that's weird. Is it something that needs to be manually changed?

**Comment by alexmacarthur** [comment]
Ah, great catch, @paulovieira! 

@LuBreGit That's set on your system level. If you're using a Mac, it'll looks something like this in your accessibility settings: 

![image](https://user-images.githubusercontent.com/8398220/150723555-14e51701-86ef-4291-9af6-14b797784a29.png)

I'm gonna close this issue since it seems we've identified the issue.
