### ISSUE TITLE
Feature: allow the `overflow` property to be given by the user

### ISSUE THREAD

**Issue by paulovieira** [alexmacarthur/slide-element#29]
# Proposed Feature or Bug

This would be similar to the `display` property (which is `block` by default, but can be overriden by the user using the options).

In practice it would useful to be able to specify `overflow: hidden` to avoid having that temporary scrollbar while the element is being shown (which causes a unpleasant jump in the text at the beginning / end of the animation).

**Comment by Eldzej** [comment]
For anyone else who runs into the problem of temporary scrollbar, until/unless this gets merged, it can be fixed (cross-browser) by this handy CSS snippet on whatever the element you are sliding

```
scrollbar-width: none;

&::-webkit-scrollbar {
  display: none;
}
```

**Comment by darvanen** [comment]
I second this request.

**Comment by darvanen** [comment]
Actually never mind, current code already checks the overflow status on the sliding element. I don't really understand why the default is auto but it doesn't really matter to me.

**Comment by AlecRust** [comment]
Yeah, why is `overflow: auto` the default anyway?

`overflow-y: hidden !important` is another crude fix.

**Comment by Eldzej** [comment]
> Yeah, why is `overflow: auto` the default anyway?
> 
> `overflow-y: hidden !important` is another crude fix.

Yes, that is also good, assuming you do not have any potentially overflowing elements inside the collapsed block (various JS selectboxes, Tippy, etc)

**Comment by alexmacarthur** [comment]
The `overflow` value is now configurable in v2.3.0. Thanks for the patience on this!

https://github.com/alexmacarthur/slide-element/releases/tag/v2.3.0
