### ISSUE TITLE
is there also a pure javascript version?

### ISSUE THREAD

**Issue by hamburger123456** [alexmacarthur/slide-element#4]
Nice tool, but i do not have any clue of typescript. Is there also a non uglyfied javascript version?

**Comment by alexmacarthur** [comment]
Hi! Unfortunately, there's not right now. You can run the TS through a REPL online and get the desired result, though: 

[Link to Pure JS](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTDYEB2BnOBfOAMyghDgCIA6AehgE8wBTbcgbgCh2AbR+AZS7AAJowDCWGCS48ocALxwAFIx4hGmGAC44ACQAqAWQAyAUVXqYAGjgQ0GHNtTos2AJTyAfInZw4PeIwAbhZGwNgw6oxQegzM2uFQwJgA5gDaALrycKnkkgCGOMDOmOpC5Na5UAXYRfYAxgV1KuTpHD5+vHDJvABKeQDuOozAyQAW8AqK7nJeKoxqGpR1ghZDI+Mcvv5dvGbzFnz0PFlTnnBzCzCU4XQ8mx3w2LwAImFgXHl0J4F5XACujHikiSyWmXkU3Rge0uh1ujCmlCEbw+XwUP3+jFcbV81AAVLj2nBcXAAGLAKCMOB5GwlAC06DURD+mDqxTg-VG6ipmG5oDybNGeVwdVI714jCElEJuOo7W2-TyRRJ0AAgpg+cVxOB-PYTq5tAAFEggMKMAA8gQgwi8M28vl8FJgfygPJK-TgRtIpsUigp2AgXGCYLt9t8QRCYQiJWisWwlEI0BMeTqox9gnCkRjTGsSREAA9gwhCaHzuZFnkhEITMENKEM9HFMWS35I5mYkwqbgANaMOgQQi6QymMtQmswAx5MCWJsl062ovN5vUahwV7YMD8lNwGCcuAAfQgO6ie+3VUKbPDGhzPOgIlkMAgcGWjAKcD+YG3u4pIEV6pSLfrKIpUXEsLgsRE3k3UZqwsRsQObN04D0M8amKGCNGUMc6yjKJ22YVJc0YPM4AAPTgABGdJXBnZssU4eD7T9ANgime4QLwacGIXBiaSabRJABTj4LwGi4Do5s8HE+1JPuPBsTgPECXtYk+E6JJal+OBRD4Pg4ApABHP5yQlbdHyYKAEygMhOXWeB8nPexgN8GU5U6d8hH5RhkOqWosE9cz0GYE5LKaUQeDyWQFEIX4nn1OBLWEM5uK2ToCg1exYR4XAFGQAAjAArRhWUoIUamSTA4JLZKSxssYtAocpRIgYILK4CB+m0chRmEERMEakD7NQ+xnmdfl7E6ygACYAFYWCE5tBt8zA9FAEESWZVlxooF8nn6ksOJnWximwYs6OLPLCuKixEmYRQ0p-YpMuYVx40TZNU0UVIezoax0QBKikpnSFoQOI54VcL7e0yKLoFC8LZAAfgauBtD+xg2PwKS5PohT8WlOAAHFgBrKk4FyjbRhsAdcsYSzGGoPJCAiWQwBIAKvjR7BrGBZJulkaltN0+6xqwfGabpuAADIqSZqJP0pEo83gCkNySK5pVlFK7MSXmojVdKsBOfpgGkVB1G0XKIADF9MDiz0TSeC0rSEG0vGqx1nVdRh3Xt71fWYZjMUB5t3M87yHL8tmokC7BWJx0Ntlq8YADVfgBbAgUSFIMiyVIAAMABIEEhPpBmGOqpjwMA8zzioAAZq5aeTQ2AAdFGN02mFtkNmyTmBU4xOMKRap444k+P7W2VJiFIbmIGhuA+4H9Pm-tBUlVVdUHvsLUxWKBEjwquc3dE0OInDobI9saPgFugTMVX0MmMDcGMd8GSJ98YGRyehE+6yGeIBH4KRXHobquAz6UhAH8cIi9JxdxpKTJ4G4qgRG3MAOoXY4BJBsFAO8plTwjD5tyXk28sBOSfowQyzAYD6zIZgEkVQ1A+kLKJAy6daFbxFgwph8Jj490XN-fYGhf4vX-goB8b9pJSVDB-WRWN5LbHfFkIUdAWRKFYaGAYiptZEL1lw-e0UuCxVXk8GAa53ifEUOQTAWBGDkDOpQp0LoPTGlNJQZ+LEjEmPaNjVy8AhDtR5AoVR6j+HVTMRYlE1jcptUwQ41e2iiiEN1lAOh3DFD30cYxXgntXFeieB4gOL9MlQABAonG2wHy82OJMTROTnE8hLgMNYFd3BI3fKcbQgT+gVQqe0D2LikDvmsD0zAc8amUmxn4xSPhiTpLQa+MCGgbBd2Ai5IikBYAPDgGMlR2A1F1CUO0ZZ9V9DGBBledoR17DZUQCJO2bjHaW2tgUV2IZBk8iSfwQQIhxAaCkDIZQI5rA3JcC9MZccZl4yJHABZlIlkjifG1J4ko5myk2dAeASiPwhIOWE05oK7AuCyAgSShonnmheeFTA7zuKfKpOvH5wgxASEBVEYFwirCrOOi9TpdFoVKXmQYhFPJTmrK5NAZFEBUVkyFCZQ2RRcDhE8usjFeYtnYs6NU5ItSlCnO0Oc4cXKiXHVJeS-JDsqVWxpXSgZuSXECBZf8yQAYgWEp5bcl6OqeBQtYEAA)
