### ISSUE TITLE
set default display

### ISSUE THREAD

**Issue by Rabbitzzc** [alexmacarthur/slide-element#5]
https://github.com/alexmacarthur/slide-element/blob/master/src/index.ts#L95

It needs to get default display value before set display.
```ts
// get default display
const defaultDisplay = window.getComputedStyle && window.getComputedStyle(element).display || 'block'

setDisplay(defaultDisplay)
```

**Comment by Rabbitzzc** [comment]
![image](https://user-images.githubusercontent.com/26913511/117264516-ddccc500-ae85-11eb-832a-22b3c3c58843.png)
This(getComputedStyle) property has good compatibility.

**Comment by alexmacarthur** [comment]
I like the idea. The only problem is that I can't access the default display value when it's required to start as `display: none`: https://github.com/alexmacarthur/slide-element#setup

**Comment by alexmacarthur** [comment]
Let me know if this release helps you out! You can now pass a custom `display` value that will be used when the element has been slid open. Before it was always set to `block`, and will remain that way by default. 

https://github.com/alexmacarthur/slide-element/releases/tag/v1.1.0
